# Generated by Django 6.0.1 on 2026-02-11 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], max_length=2, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('manager', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateTimeField(blank=True, null=True)),
                ('flight_date_str', models.CharField(blank=True, max_length=50, null=True)),
                ('takeoff_time', models.DateTimeField(blank=True, null=True)),
                ('takeoff_name', models.CharField(blank=True, max_length=50, null=True)),
                ('landing_time', models.DateTimeField(blank=True, null=True)),
                ('landing_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paraglider', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_olc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_olc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_olc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_from_takeoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_takeoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitute_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitute_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_avarage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flight_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_content', models.BinaryField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragliding.pilot')),
            ],
        ),
    ]
