# Generated by Django 6.0.1 on 2026-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('manifacture', models.CharField(blank=True, max_length=50, null=True)),
                ('wing_class', models.CharField(blank=True, max_length=50, null=True)),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
                ('safety', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_max', models.IntegerField(blank=True, null=True)),
                ('weight_min', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
