# Generated by Django 6.0.1 on 2026-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0002_wing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wing',
            name='manifacture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wing',
            name='wing_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
