# Generated by Django 6.0.1 on 2026-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0003_alter_wing_manifacture_alter_wing_wing_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
