# Generated by Django 6.0.4 on 2026-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0004_alter_wing_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('harness_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_max', models.IntegerField(blank=True, null=True)),
                ('weight_min', models.IntegerField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
