# Generated by Django 6.0.1 on 2026-02-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
