# Generated by Django 6.0.1 on 2026-02-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_card_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='url',
            new_name='page',
        ),
    ]
