# Generated by Django 6.0.1 on 2026-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_url_card_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
