# Generated by Django 6.0.1 on 2026-02-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_card_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='page',
        ),
    ]
