# Generated by Django 6.0.1 on 2026-02-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_card_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='disabled',
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
