# Generated by Django 6.0.1 on 2026-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_card_disabled_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(blank=True, default='Paragliding', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
